name: dcase2021_task2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _pytorch_select=0.1=cpu_0
  - absl-py=0.12.0=pyhd8ed1ab_0
  - aiohttp=3.7.4=py37h27cfd23_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py37h5e8e339_2
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - audioread=2.1.9=py37h89c1867_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py37hb5d75c8_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2021.5.30=ha878542_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - certifi=2021.5.30=py37h89c1867_0
  - cffi=1.14.5=py37h261ae71_0
  - chardet=3.0.4=py37he5f6b98_1008
  - click=8.0.1=py37h89c1867_0
  - cryptography=3.4.7=py37h5d9358c_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - cycler=0.10.0=py_2
  - dataclasses=0.8=pyhc8e2a94_1
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - ffmpeg=4.3.1=hca11adc_2
  - freetype=2.10.4=h0708190_1
  - fsspec=2021.6.0=pyhd8ed1ab_0
  - future=0.18.2=py37h89c1867_3
  - gettext=0.19.8.1=h0b5b191_1005
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.17=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-auth=1.30.0=pyh44b312d_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.33.2=py37haffed2e_2
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=4.5.0=py37h89c1867_0
  - intel-openmp=2019.4=243
  - ipykernel=5.5.5=py37h085eea5_0
  - ipython=7.24.1=py37h085eea5_0
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py37h89c1867_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py37h89c1867_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kiwisolver=1.3.1=py37h2527ec5_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=1_h6e990d7_netlib
  - libcblas=3.9.0=3_h893e4fe_netlib
  - libdeflate=1.7=h7f98852_5
  - libffi=3.3=he6710b0_2
  - libflac=1.3.3=h9c3ff4c_1
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libgomp=9.3.0=h5101ec6_17
  - liblapack=3.9.0=3_h893e4fe_netlib
  - libllvm10=10.0.1=he513fc3_3
  - libmklml=2019.0.5=0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.14.0=h8c45485_0
  - librosa=0.8.1=pyhd8ed1ab_0
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.3.0=hf544144_1
  - libuv=1.40.0=h7b6447c_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h7f98852_2
  - llvmlite=0.36.0=py37h9d7f4d0_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=2.0.1=py37h5e8e339_0
  - matplotlib-base=3.4.2=py37hdd32ed1_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py37h5e8e339_1003
  - mkl=2020.2=256
  - multidict=5.1.0=py37h27cfd23_2
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py37h89c1867_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=hff7bd54_1
  - notebook=6.4.0=pyha770c72_0
  - numba=0.53.1=py37h134767a_0
  - numpy=1.19.4=py37h7e9df27_1
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.4=py37h2531618_0
  - pandoc=2.14.0.1=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.2.0=py37h4600e1f_1
  - pip=21.1.1=py37h06a4308_0
  - pooch=1.4.0=pyhd8ed1ab_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - protobuf=3.14.0=py37h2531618_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydeprecate=0.3.0=pyhd8ed1ab_0
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py37h5e8e339_2
  - pysocks=1.7.1=py37h89c1867_3
  - pysoundfile=0.10.3.post1=pyhd3deb0d_0
  - python=3.7.10=hdb3f193_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.8.1=py3.7_cuda11.1_cudnn8.0.5_0
  - pytorch-lightning=1.3.5=pyhd8ed1ab_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.3.1=py37hb5d75c8_1
  - pyzmq=22.1.0=py37h336d617_0
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - resampy=0.2.2=py_0
  - rsa=4.7.2=pyh44b312d_0
  - scikit-learn=0.24.2=py37ha9443f7_0
  - scipy=1.5.3=py37h8911b10_0
  - send2trash=1.5.0=py_0
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.35.4=hdfb4753_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - terminado=0.10.0=py37h89c1867_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.8.1=py37
  - torchmetrics=0.3.2=pyhd8ed1ab_0
  - torchvision=0.2.2=py_3
  - tornado=6.1=py37h5e8e339_1
  - tqdm=4.61.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py37h4abf009_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - alembic==1.4.1
    - cloudpickle==1.6.0
    - databricks-cli==0.14.3
    - docker==5.0.0
    - flask==2.0.1
    - greenlet==1.1.0
    - gunicorn==20.1.0
    - itsdangerous==2.0.1
    - mako==1.1.4
    - mlflow==1.17.0
    - prometheus-flask-exporter==0.18.2
    - python-editor==1.0.4
    - querystring-parser==1.2.4
    - sqlalchemy==1.4.17
    - sqlparse==0.4.1
    - tabulate==0.8.9
    - websocket-client==1.0.1
prefix: /home/paul/miniconda3/envs/dcase2021_task2
